In [1]:
import numpy as np

# Adjacency list for the graph (undirected)
adj_list = {
    0: [1, 2],  # Neighbors of node 0
    1: [0, 3],  # Neighbors of node 1
    2: [0, 3],  # Neighbors of node 2
    3: [1, 2]   # Neighbors of node 3
}

# Number of nodes
n = 4

# Initialize the weight matrix W
W = np.zeros((n, n))

# Calculate the weight matrix W
for i in range(n):
    neighbors = adj_list[i]
    weight = 1 / len(neighbors)  # Calculate weight based on number of neighbors
    for j in neighbors:
        W[i, j] = weight


# Create the incidence matrix B
# For a graph with 4 edges (since it's a square graph)
edges = [(0, 1), (1, 3), (3, 2), (2, 0)]
m = len(edges)


# Compute the incidence matrix B
B = np.zeros((m, n))
for idx, (i, j) in enumerate(edges):
    weight = np.sqrt(W[i, j])  # Calculate sqrt of the weight
    B[idx, i] = weight
    B[idx, j] = -weight

# Calculate the Laplacian matrix L
Lambda = B.T @ B

# Print the matrices
print("Weight Matrix W:")
print(W)
print("\nIncidence Matrix B:")
print(B)
print("\nLaplacian Matrix L:")
print(Lambda)

Weight Matrix W:
[[0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]
 [0.5 0.  0.  0.5]
 [0.  0.5 0.5 0. ]]

Incidence Matrix B:
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.70710678  0.         -0.70710678]
 [ 0.          0.         -0.70710678  0.70710678]
 [-0.70710678  0.          0.70710678  0.        ]]

Laplacian Matrix L:
[[ 1.  -0.5 -0.5  0. ]
 [-0.5  1.   0.  -0.5]
 [-0.5  0.   1.  -0.5]
 [ 0.  -0.5 -0.5  1. ]]
